### ISSUE TITLE
BUG: No Attribute label

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/ocr-pipeline#24]
# Description

If the Pipeline runs into Exception, even another exception is thrown like:

```
Traceback (most recent call last):
  File "ocr_pipeline.py", line 399, in _execute_pipeline
    profile_result = profile(step.execute)
  File "ocr_pipeline.py", line 372, in profile
    func()
  File "/opt/ocr-pipeline/lib/ocr_step.py", line 378, in execute
    raise StepException(f"Invalid data: {sys.exc_info()[0]}")
lib.ocr_step.StepException: Invalid data: <class 'requests.exceptions.ConnectionError'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "ocr_pipeline.py", line 425, in _execute_pipeline
    step.label,
AttributeError: 'StepEstimateOCR' object has no attribute 'label'

```

**Comment by M3ssman** [comment]
Actually, no step got this attribute, so just drop it
